[package]
name = "chainx-sub-parse"
version = "0.1.0"
authors = ["ChainX <https://chainx.org>"]
#edition = "2018"

[dependencies]
env_logger = "0.6"
log = "0.4"
error-chain = "0.12"
redis = "0.9"
hex = "0.3"
parity-codec = "2.1"
parity-codec-derive = "2.1"
parking_lot = "0.7"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
strum = "0.13"
strum_macros = "0.13"

substrate-primitives = { git = "https://github.com/paritytech/substrate" }
sr-std = { git = "https://github.com/paritytech/substrate" }
sr-primitives = { git = "https://github.com/paritytech/substrate" }

srml-metadata = { git = "https://github.com/paritytech/substrate" }
