[package]
name = "chainx-sub-parse"
version = "0.1.0"
authors = ["ChainX <https://chainx.org>"]
edition = "2018"

[dependencies]
log = "0.4"
log4rs = "0.8"
failure = "0.1"
failure_derive = "0.1"
redis = "0.9"
hex = "0.3"
parity-codec = "3.0"
parity-codec-derive = "3.0"
parking_lot = "0.7"
reqwest = "0.9"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
strum = "0.13"
strum_macros = "0.13"
jsonrpc-core = "10.0"
jsonrpc-http-server = "10.0"

sr-primitives = { git = "https://github.com/paritytech/substrate", rev = "e8b558c" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", rev = "e8b558c" }

[dev-dependencies]
hyper = "0.12"

[features]
default = ["std"]
std = []
