[package]
name = "chainx-sub-parse"
version = "0.1.0"
authors = ["ChainX <https://chainx.org>"]

[dependencies]
log = "0.4"
log4rs = "0.8"
error-chain = "0.12"
redis = "0.9"
hex = "0.3"
parity-codec = "2.1"
parity-codec-derive = "2.1"
parking_lot = "0.7"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
strum = "0.13"
strum_macros = "0.13"

substrate-primitives = { git = "https://github.com/paritytech/substrate", rev = "4ee928f" }
sr-std = { git = "https://github.com/paritytech/substrate", rev = "4ee928f" }
sr-primitives = { git = "https://github.com/paritytech/substrate", rev = "4ee928f" }
srml-support = { git = "https://github.com/paritytech/substrate", rev = "4ee928f" }
srml-metadata = { git = "https://github.com/paritytech/substrate", rev = "4ee928f" }

[features]
default = ["std"]
std = []
