[package]
name = "chainx-sub-parse"
version = "0.1.0"
authors = ["ChainX <https://chainx.org>"]
edition = "2018"

[dependencies]
log = "0.4"
log4rs = "0.8"
failure = "0.1"
failure_derive = "0.1"
redis = "0.10"
hex = "0.3"
byteorder = "1.3"
parity-codec = "3.4"
parity-codec-derive = "3.3"
parking_lot = "0.7"
reqwest = "0.9"
semver = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
strum = "0.15"
strum_macros = "0.15"
jsonrpc-core = "10.1"
jsonrpc-derive = "10.1"
jsonrpc-http-server = "10.1"
diesel = { version = "1.4", optional = true }
dotenv = { version = "0.13", optional = true }

# Substrate (the versoin used by ChainX)
sr-primitives = { git = "https://github.com/chainpool/substrate", rev = "116529a9" }
substrate-primitives = { git = "https://github.com/chainpool/substrate", rev = "116529a9" }

# bitcoin (the latest version of master branch of light-bitcoin)
btc-chain = { package = "chain", git = "https://github.com/chainx-org/light-bitcoin" }
btc-keys = { package = "keys", git = "https://github.com/chainx-org/light-bitcoin" }

[dev-dependencies]
clap = "2"
hyper = "0.12"

[features]
default = ["std"]
std = []
pgsql = [
    "diesel/postgres",
    "diesel/serde_json",
    "dotenv",
]
