[package]
name = "chainx-sub-parse"
version = "0.1.0"
authors = ["ChainX <https://chainx.org>"]
#edition = "2018"

[dependencies]
env_logger = "0.6"
log = "0.4"
error-chain = "0.12"
redis = "0.9"
crossbeam = "0.5"
hex = "0.3"
parity-codec = "2.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.9"

substrate-metadata = { git = "https://github.com/paritytech/substrate", rev = "4b34e0f2" }
